name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout skoria-site repo
        uses: actions/checkout@v2
        with:
          repository: pheelwell/skoria-site
          path: skoria-site

      - name: Set Git user
        run: |
          git config --global user.email "dev@bot.de"
          git config --global user.name "Dev Bot"

      - name: Update submodule
        run: |
          cd skoria-site
          git submodule update --init --recursive
          git submodule foreach git pull origin main --ff-only
          git add .
          git commit -m "Update skoria submodule"
          git push origin HEAD:main
